CREATE TABLE IF NOT EXISTS participants (
	game_id BIGINT NOT NULL REFERENCES matches (game_id) ON DELETE CASCADE,
	champion_id INTEGER NOT NULL,
	kills INTEGER NOT NULL,
	deaths INTEGER NOT NULL,
	assists INTEGER NOT NULL,
	total_minions_killed INTEGER NOT NULL,
	double_kills INTEGER NOT NULL,
	triple_kills INTEGER NOT NULL,
	quadra_kills INTEGER NOT NULL,
	penta_kills INTEGER NOT NULL,
	item0 INTEGER NOT NULL,
	item1 INTEGER NOT NULL,
	item2 INTEGER NOT NULL,
	item3 INTEGER NOT NULL,
	item4 INTEGER NOT NULL,
	item5 INTEGER NOT NULL,
	item6 INTEGER NOT NULL,
	summoner1_id INTEGER NOT NULL,
	summoner2_id INTEGER NOT NULL,
	lane TEXT NOT NULL,
	participant_id INTEGER NOT NULL,
	puuid VARCHAR(78) NOT NULL,
	riot_id_game_name TEXT NOT NULL,
	riot_id_tagline TEXT NOT NULL,
	total_damage_dealt_to_champions INTEGER NOT NULL,
	total_damage_taken INTEGER NOT NULL,
	win BOOLEAN NOT NULL,
	PRIMARY KEY (game_id, participant_id)
);
