// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3) {
  return window['go']['riot']['RiotClient']['AddAccount'](arg1, arg2, arg3);
}

export function ListAccounts(arg1) {
  return window['go']['riot']['RiotClient']['ListAccounts'](arg1);
}
