// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAccounts(arg1:models.LeagueOfLegendsAccount):Promise<Array<models.LeagueOfLegendsAccount>>;
